title: Things Might Get BukzWildAF
author: BukzWildAF
email: N/A
description: > # this means to ignore newlines until "baseurl:"
  This is the GitHub Pages blog for BukzWildAF

# social links
twitter_username: N/A
github_username:  BukzWildAF

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
